### ISSUE TITLE
isKotlinProject is not detecting the kotlin subfolder in the testFixtures source set or a source set setup by the JVM Test Suite Plugin

### ISSUE THREAD

**Issue by MartinAhrer** [cloudflightio/autoconfigure-gradle-plugin#126]
The Kotlin plugin is not applied when a testFixtures source set has been applied. It is also not applied when any other source set setup by the JVM Test Suite Plugin is added to a project.

It works when project (main) source is Kotlin but generally not when the project is a Java project with only Kotlin being used  for testing.
A (dirty) hack is to add a src/test/kotlin folder (empty) so the Kotlin plugin is applied or obviously manually applying the plugin to the project.

Suggesting to match `src/*/kotlin` or iterating the existing source sets if the life-cycle allows.

**Comment by haraldradi** [comment]
now the "api" configuration is not available anymore: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

**Comment by cgrabmann** [comment]
Since this was opened without comment, I will close it again.

If it should be opened again, please provide a reason.
