### ISSUE TITLE
Target compatibility of compileJava does not match with kaptGenerateStubsKotlin

### ISSUE THREAD

**Issue by klu2** [cloudflightio/autoconfigure-gradle-plugin#31]
It seems that we are missing some explicit setting for the target compatibility when using kotlin annoation processing (kapt). This happens with all default settings applied (i.e. `JavaLanuage.of(11)`)

```
'compileJava' task (current target is 11) and 'kaptGenerateStubsKotlin' task (current target is 1.8) 
jvm target compatibility should be set to the same Java version.
```

**Comment by cgrabmann** [comment]
Found the seemingly related issue: https://youtrack.jetbrains.com/issue/KT-51104/Docs-Build-Tools-Gradle-Setting-toolchain-via-Java-extension-doe
