### ISSUE TITLE
Missing Artifacts with 0.7.0 and 0.7.1

### ISSUE THREAD

**Issue by guenhter** [cloudflightio/autoconfigure-gradle-plugin#94]
Hi,

when using the plugin version 0.7.0 or 0.7.1, the following error appears:

```
* What went wrong:
A problem occurred configuring root project 'kotlin-noob'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find io.cloudflight.json:json-wrapper:0.3.5.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/io/cloudflight/json/json-wrapper/0.3.5/json-wrapper-0.3.5.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > io.cloudflight.autoconfigure-gradle:io.cloudflight.autoconfigure-gradle.gradle.plugin:0.7.1 > io.cloudflight.gradle:autoconfigure:0.7.1
         project : > io.cloudflight.autoconfigure-gradle:io.cloudflight.autoconfigure-gradle.gradle.plugin:0.7.1 > io.cloudflight.gradle:autoconfigure:0.7.1 > io.cloudflight.license.gradle:license-gradle-plugin:1.1.0
```

It seems like that version `0.3.5` of the library https://repo.gradle.org/ui/native/jcenter/io/cloudflight/json/json-wrapper is not yet released, but this plugin depends on it.

Could you please have a look. Thx

**Comment by klu2** [comment]
0.3.5 of the Json-Wrapper is released on MavenCentral: https://search.maven.org/artifact/io.cloudflight.json/json-wrapper/0.3.5/jar and it's also there in the Gradle-Repo: https://repo.gradle.org/ui/native/jcenter/io/cloudflight/json/json-wrapper/0.3.5/, that all seems fine, and we're using the plugin without issues in a lot of projects.

What changed with [version 0.7.0](https://github.com/cloudflightio/autoconfigure-gradle-plugin/releases/tag/v0.7.0) is that you need Java 11 at runtime to run the plugin (and so does the json-wrapper library). Can it be you're attempting to run the plugin with Java 8?

**Comment by guenhter** [comment]
Thx. I can confirm that the lib is now under  https://repo.gradle.org/ui/native/jcenter/io/cloudflight/json/json-wrapper  but I'm absolutely certain that last week when I browsed to it, the 0.3.5 version was not there (sadly I haven't taken a screenshot).

Anyway, it works now without any action from my end. Thx
